services:
  backend:
    image: eshpulatov/fraud-protection-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      MAIN_DATASOURCE_URL: jdbc:postgresql://db:5432/fraud_protection
      MAIN_DATASOURCE_USERNAME: postgres
      MAIN_DATASOURCE_PASSWORD: 123

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: fraud_protection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network


  redis:
    container_name: redis
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres-data:
  redis-data:

networks:
  app-network: